version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gateway:
    image: micro-services
    ports:
      - "8090:8090"
    depends_on:
      - kafka
      - db
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: gateway
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: demo
      DATASOURCE_PASSWORD: demo
  pizza:
    image: micro-services
    depends_on:
      - kafka
      - db
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: pizza
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: demo
      DATASOURCE_PASSWORD: demo
  delivery:
    image: micro-services
    depends_on:
      - kafka
      - db
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: delivery
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: demo
      DATASOURCE_PASSWORD: demo
  payment:
    image: micro-services
    depends_on:
      - kafka
      - db
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: payment
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: demo
      DATASOURCE_PASSWORD: demo
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db'
      - 'POSTGRES_PASSWORD=demo'
      - 'POSTGRES_USER=demo'
    ports:
      - '5432:5432'

