#version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: gateway
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: demo
      DATASOURCE_PASSWORD: demo
  pizza:
    container_name: pizza
    build:
      context: ./gateway
    depends_on:
      - kafka
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: order
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: demo
      DATASOURCE_PASSWORD: demo
  delivery:
    container_name: delivery
    build:
      context: ./gateway
    depends_on:
      - kafka
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: delivery
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: demo
      DATASOURCE_PASSWORD: demo
  payment:
    container_name: payment
    build:
      context: ./gateway
    depends_on:
      - kafka
    environment:
      TRAVEL_KAFKA_SERVER: kafka:9092
      TRAVEL_SERVICE_TYPE: payment
      DATASOURCE_URL: jdbc:postgresql://db:5432/db
      DATASOURCE_USERNAME: demo
      DATASOURCE_PASSWORD: demo
  user_service:
    container_name: user_service
    build:
      context: ./rest/user_interface
    ports:
      - "8083:8083"
    depends_on:
      - gateway
  payment_soap:
    container_name: payment_soap
    build:
      context: ./paymentSOAP
    ports:
      - "8080:8080"
    depends_on:
      - payment