/// *
// * Travel mircro service
// * Micro service to book a travel
// *
// * OpenAPI spec version: 1.0.0
// * Contact: supportm@bp.org
// *
// * NOTE: This class is auto generated by the swagger code generator program.
// * https://github.com/swagger-api/swagger-codegen.git
// * Do not edit the class manually.
// */
//
//package org.bp.pizza.model;
//
//import java.util.Objects;
//
//import com.fasterxml.jackson.annotation.JsonProperty;
//import com.fasterxml.jackson.annotation.JsonPropertyOrder;
//
///**
// * BookDeliveryRequest
// */
//
//@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-06T08:44:40.322365400+01:00[Europe/Warsaw]")
//public class BookDeliveryRequest {
//  @JsonProperty("person")
//  private Person person = null;
//
////  @JsonProperty("flight")
////  private Flight flight = null;
//
//  @JsonPropertyOrder("delivery")
//  private Delivery delivery = null;
//
//
//  public BookDeliveryRequest person(Person person) {
//    this.person = person;
//    return this;
//  }
//
//   /**
//   * Get person
//   * @return person
//  **/
//
//  public Person getPerson() {
//    return person;
//  }
//
//  public void setPerson(Person person) {
//    this.person = person;
//  }
//
////  public BookDeliveryRequest flight(Flight flight) {
////    this.flight = flight;
////    return this;
////  }
//public BookDeliveryRequest delivery(Delivery delivery) {
//  this.delivery = delivery;
//  return this;
//}
//
//   /**
//   * Get flight
//   * @return flight
//  **/
//
////  public Flight getFlight() {
////    return flight;
////  }
////
////  public void setFlight(Flight flight) {
////    this.flight = flight;
////  }
//   public Delivery getDelivery() {
//     return delivery;
//   }
//
//  public void setDelivery(Delivery delivery) {
//    this.delivery = delivery;
//  }
//
//  @Override
//  public boolean equals(java.lang.Object o) {
//    if (this == o) {
//      return true;
//    }
//    if (o == null || getClass() != o.getClass()) {
//      return false;
//    }
//    BookDeliveryRequest bookDeliveryRequest = (BookDeliveryRequest) o;
//    return Objects.equals(this.person, bookDeliveryRequest.person) &&
//            Objects.equals(this.delivery, bookDeliveryRequest.delivery);
////        Objects.equals(this.flight, bookDeliveryRequest.flight);
//  }
//
//  @Override
//  public int hashCode() {
//    return Objects.hash(person, delivery);
//  }
//
//
//  @Override
//  public String toString() {
//    StringBuilder sb = new StringBuilder();
//    sb.append("class BookDeliveryRequest {\n");
//
//    sb.append("    person: ").append(toIndentedString(person)).append("\n");
//    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
//    sb.append("}");
//    return sb.toString();
//  }
//
//  /**
//   * Convert the given object to string with each line indented by 4 spaces
//   * (except the first line).
//   */
//  private String toIndentedString(java.lang.Object o) {
//    if (o == null) {
//      return "null";
//    }
//    return o.toString().replace("\n", "\n    ");
//  }
//
//}
