/*
 * Travel mircro service
 * Micro service to book a travel
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.pizza.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;
import java.util.Objects;


@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-12-06T08:44:40.322365400+01:00[Europe/Warsaw]")
public class Pizza {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("size")
  private Float size = null;

  @JsonProperty("ingredients")
  private String ingredients = null;

  @JsonProperty("prize")
  private Float prize = null;

  @JsonProperty("prepTime")
  private OffsetDateTime prepTime = null;

  public Pizza name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Pizza city(Float size) {
    this.size = size;
    return this;
  }

   /**
   * Get city
   * @return city
  **/

  public Float getSize() {
    return size;
  }

  public void setSize(Float size) {
    this.size = size;
  }

  public Pizza prize(Float prize) {
    this.prize = prize;
    return this;
  }

   /**
   * Get country
   * @return country
  **/

  public Float getPrize() {
    return prize;
  }

  public void setPrize(Float prize) {
    this.prize = prize;
  }

  public Pizza ingredients(String ingredients) {
    this.ingredients = ingredients;
    return this;
  }

   /**
   * Get address
   * @return address
  **/

  public String getIngredients() {
    return ingredients;
  }

  public void setIngredients(String ingredients) {
    this.ingredients = ingredients;
  }

  public Pizza prepTime(OffsetDateTime prepTime) {
    this.prepTime = prepTime;
    return this;
  }

   /**
   * Get checkOut
   * @return checkOut
  **/

  public OffsetDateTime getPrepTime() {
    return prepTime;
  }

  public void setPrepTime(OffsetDateTime prepTime) {
    this.prepTime = prepTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pizza pizza = (Pizza) o;
    return Objects.equals(this.name, pizza.name) &&
        Objects.equals(this.size, pizza.size) &&
        Objects.equals(this.prize, pizza.prize) &&
        Objects.equals(this.ingredients, pizza.ingredients) &&
        Objects.equals(this.prepTime, pizza.prepTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, size, prize, ingredients, prepTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pizza {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    city: ").append(toIndentedString(size)).append("\n");
    sb.append("    country: ").append(toIndentedString(prize)).append("\n");
    sb.append("    ingredients: ").append(toIndentedString(ingredients)).append("\n");
    sb.append("    checkOut: ").append(toIndentedString(prepTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
